# Generated by Django 4.0.2 on 2022-02-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos/%Y/%M/%d/')),
                ('facebook', models.URLField(max_length=250)),
                ('google', models.URLField(max_length=250)),
                ('twitter', models.URLField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
