# Generated by Django 4.0.2 on 2022-02-17 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_Tital', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('PU', 'punjab'), ('KPK', 'khyber pukhtankhwa'), ('BL', 'blochistan'), ('FD', 'fedral Territory'), ('SN', 'sindh'), ('KS', 'kashmir')], max_length=300)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discreption', models.TextField(max_length=5000)),
                ('car_photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('car_photo1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('features', models.CharField(choices=[('Cruise control', 'Cruise control'), ('Audio interface', 'Audio interface'), ('Airbags', 'Airbags'), ('Air condition', 'Air condition'), ('seat heating', 'seat heating'), ('Alram system', 'Alram system'), ('parkassist', 'parkassist'), ('power steering', 'power steering'), ('revers camera', 'revers camera'), ('Direct fuel injection', 'Direct fuel injection'), ('Auto start/stop', 'Auto start/stop'), ('wind deflector', 'wind deflector'), ('Bluetooth handset', 'Bluetooth handset')], max_length=100)),
                ('body_style', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('interior', models.CharField(max_length=200)),
                ('miles', models.IntegerField()),
                ('door', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100)),
                ('passangers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=200)),
                ('millage', models.IntegerField()),
                ('fule_type', models.CharField(max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
